-- Add migration script here
ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE servers ALTER COLUMN id DROP DEFAULT; 
ALTER TABLE channels ALTER COLUMN id DROP DEFAULT;
ALTER TABLE messages ALTER COLUMN id DROP DEFAULT;